/**
 * Sea Power .ini file generators for Task Force Mode campaigns.
 *
 * Syntax sources (see docs/REFERENCE_INDEX.md):
 * - Task Force Mode campaign/roster structure: skill reference
 *   `skills/sea-power-campaign-planning/references/task-force-mode.md`.
 * - Mission trigger syntax (`Condition_<Name>_Type`, `ConditionsCompleted`,
 *   `Action_*`, delayed-exit pattern), `[Language_en]` `Title|Body|Button`
 *   message format, and vessel keys: Steam community mission guides
 *   (Mission Creation Community Guide; Triggers and Conditions Guide).
 * - Player start defaults (radars off, stores full, damage none):
 *   `references/mission-generation.md`.
 *
 * Unknown [Mission]-level keys (world location, date, environment) are NOT
 * invented: they are copied from a read-only base-game reference mission
 * when one is provided (`mergeReferenceMissionKeys`).
 */

import type { UnitCatalogEntry } from "../catalog/unitCatalog";

// ---------------------------------------------------------------------------
// Campaign-level inputs
// ---------------------------------------------------------------------------

export interface CampaignFileSpec {
  campaignFolder: string;
  displayName: string;
  defaultTaskForceName: string;
  difficultyPresets: string[]; // e.g. ["Easy", "Moderate", "Difficult"]
  defaultPreset: string;
  startingPoints: number;
  pointCap: number;
  missionFileName: string; // file name inside missions/
  missionDisplayName: string;
  threat: { ship: boolean; air: boolean; sub: boolean; land: boolean };
  completionPoints: number;
}

/** Difficulty presets follow the documented section layout. */
function difficultySection(id: string, startingPoints: number, pointCap: number): string {
  const modifiers: Record<string, { repair: number; points: number }> = {
    Easy: { repair: 0.5, points: Math.round(startingPoints * 1.25) },
    Moderate: { repair: 1, points: startingPoints },
    Difficult: { repair: 1.5, points: Math.round(startingPoints * 0.8) },
  };
  const m = modifiers[id] ?? { repair: 1, points: startingPoints };
  return [
    `[TaskForceModeDifficulty_${id}]`,
    `Name=${id}`,
    `StartingPoints=${m.points}`,
    `PointCap=${Math.max(pointCap, m.points)}`,
    `ShipIncludesAirwing=True`,
    `PurchaseLoadouts=True`,
    `InitialUnlockedLoadouts=Default|Early`,
    `RepairCostModifier=${m.repair}`,
    `UnitDecommissionPointReturnModifier=0.25`,
    `UnitDismissPointReturnModifier=0.5`,
    `CrewSkillInitial=Trained`,
    ``,
  ].join("\n");
}

export function generateCampaignIni(spec: CampaignFileSpec): string {
  const threatLine = (label: string, on: boolean, weight: number) =>
    `TaskForceModeThreatProfile${label}=${on ? `True,${weight}` : "False"}`;
  const lines = [
    `; Generated by Sea Power Dynamic Campaign (playtest export).`,
    `; Campaign: ${spec.displayName}`,
    ``,
    `[Campaign]`,
    `Type=Linear`,
    `Length=1`,
    ``,
    `[TaskForceMode]`,
    `Enabled=True`,
    `DefaultTaskForceName=${spec.defaultTaskForceName}`,
    `CommanderSettingsFile=commander_settings.ini`,
    `RosterFile=player_task_force_roster.ini`,
    `TaskForceDifficultyPresets=${spec.difficultyPresets.join("|")}`,
    `DefaultTaskForceDifficultyPreset=${spec.defaultPreset}`,
    `StartingPoints=${spec.startingPoints}`,
    `PointCap=${spec.pointCap}`,
    `ShipIncludesAirwing=True`,
    `PurchaseLoadouts=True`,
    ``,
  ];
  for (const preset of spec.difficultyPresets) {
    lines.push(difficultySection(preset, spec.startingPoints, spec.pointCap));
  }
  lines.push(
    `[Mission1]`,
    `MissionFile=campaigns/${spec.campaignFolder}/missions/${spec.missionFileName}`,
    `TaskForceModeMissionGenerationType=Generated`,
    `IsUnlocked=True`,
    `TaskForceModeIncludesTaskForce=True`,
    `TaskForceModeIncludesAirwing=False`,
    `TaskForceModeIncludesSubmarine=False`,
    threatLine("Ship", spec.threat.ship, 3),
    threatLine("Air", spec.threat.air, 2),
    threatLine("Sub", spec.threat.sub, 3),
    threatLine("Land", spec.threat.land, 1),
    `TaskForceModeRearm=True`,
    `TaskForceModeRepair=True`,
    `TaskForceModeEnableTaskForceBuilder=True`,
    `TaskForceModeCompletionPoints=${spec.completionPoints}`,
    `TaskForceModeCompletionCapPoints=${spec.completionPoints}`,
    ``,
  );
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Roster
// ---------------------------------------------------------------------------

export interface RosterSpec {
  /** Discovered, export-eligible units only — validated upstream. */
  vessels: UnitCatalogEntry[];
  submarines: UnitCatalogEntry[];
  aircraft: UnitCatalogEntry[];
  helicopters: UnitCatalogEntry[];
  /** Fallback cost when a discovered unit has no parsed TaskForceCost. */
  fallbackCost: number;
}

function rosterLine(u: UnitCatalogEntry, refs: string[], fallbackCost: number): string {
  const cost = u.taskForceCost ?? fallbackCost;
  const refPart = refs.length > 0 ? refs.join(",") : "";
  return `${u.unitType}=${refPart}|${cost}`;
}

export function generateRosterIni(spec: RosterSpec): string {
  const section = (
    name: string,
    units: UnitCatalogEntry[],
    refsOf: (u: UnitCatalogEntry) => string[],
  ): string[] =>
    units.length === 0
      ? []
      : [`[${name}]`, ...units.map((u) => rosterLine(u, refsOf(u), spec.fallbackCost)), ``];

  return [
    `; Generated player Task Force Builder roster.`,
    `; Ships/submarines list VariantReference names; aircraft/helicopters list SquadronReference names.`,
    ``,
    ...section("AllowedVessels", spec.vessels, (u) => u.variants),
    ...section("AllowedSubmarines", spec.submarines, (u) => u.variants),
    ...section("AllowedAircraft", spec.aircraft, (u) => u.squadrons),
    ...section("AllowedHelicopters", spec.helicopters, (u) => u.squadrons),
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Commander settings (schema unverified — minimal placeholder)
// ---------------------------------------------------------------------------

export function generateCommanderSettingsIni(commanderName: string): string {
  return [
    `; Minimal commander settings placeholder generated for playtest.`,
    `; The commander_settings.ini schema is not yet verified against game`,
    `; examples; the campaign references this file as required by`,
    `; [TaskForceMode] CommanderSettingsFile. Compare with a base-game`,
    `; campaign's commander_settings.ini and extend as needed.`,
    `; Commander: ${commanderName}`,
    ``,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Mission
// ---------------------------------------------------------------------------

export interface MissionUnitSpec {
  sectionName: string; // e.g. Taskforce1Vessel1
  unitType: string;
  variantReference?: string;
  relativePositionNM: [number, number, number];
  heading: number;
  telegraph: number;
  isAnchor: boolean;
}

export interface MissionSpec {
  missionDisplayName: string;
  briefing: string;
  objectiveText: string;
  playerUnits: MissionUnitSpec[]; // [0] must be the anchor
  enemyUnits: MissionUnitSpec[];
  /** Patrol duration in seconds for the guaranteed completion path. */
  patrolSeconds: number;
  /** Seconds after completion before the mission exits. */
  exitDelaySeconds: number;
  introDelaySeconds: number;
}

function unitSection(taskforce: string, u: MissionUnitSpec, isPlayer: boolean): string {
  const lines = [
    `[${u.sectionName}]`,
    `Type=${u.unitType}`,
  ];
  if (u.variantReference) lines.push(`VariantReference=${u.variantReference}`);
  lines.push(
    `MissionType=NoMission`,
    // Conservative player defaults per mission-generation reference:
    // radars off, stores full, no damage. Enemy keeps radars on so it can
    // fight, weapons free.
    `WeaponStatus=Free`,
    `RadarsActive=${isPlayer ? "False" : "True"}`,
    `CrewSkill=Trained`,
    `Stores=Full`,
    `Damage=None`,
    `RelativePositionInNM=${u.relativePositionNM.join(",")}`,
    `Heading=${u.heading}`,
    `Telegraph=${u.telegraph}`,
  );
  if (u.isAnchor) lines.push(`TaskForceModeAnchor=True`);
  void taskforce;
  lines.push(``);
  return lines.join("\n");
}

/**
 * Generate a Task Force Mode `Generated` mission.
 *
 * Structure (all syntax verified against community guides):
 * - Trigger1: timed intro message.
 * - Trigger2: completion = patrol timer OR all enemy vessels destroyed —
 *   the mission stays completable even if enemies never engage. Completion
 *   fires the completion message, objective complete, victory, and enables +
 *   reactivates the delayed-exit trigger.
 * - Trigger3 (Disabled=True): delayed exit after `exitDelaySeconds`.
 */
export function generateMissionIni(spec: MissionSpec): string {
  const enemySections = spec.enemyUnits.map((u) => u.sectionName);
  const hasEnemies = enemySections.length > 0;

  const missionLines = [
    `; Generated Task Force Mode mission (playtest export).`,
    ``,
    `[Mission]`,
    `PlayerTaskforce=Taskforce1`,
    `NumberOfTaskforce1Vessels=${spec.playerUnits.length}`,
  ];
  if (hasEnemies) {
    missionLines.push(`NumberOfTaskforce2Vessels=${spec.enemyUnits.length}`);
  }
  missionLines.push(`NumberOfTriggers=3`, ``);

  const unitSections = [
    ...spec.playerUnits.map((u) => unitSection("Taskforce1", u, true)),
    ...spec.enemyUnits.map((u) => unitSection("Taskforce2", u, false)),
  ];

  const completionConditions = hasEnemies
    ? `<PatrolComplete> OR <EnemyDestroyed>`
    : `<PatrolComplete>`;

  const triggerSections = [
    [
      `[Trigger1]`,
      `Name=Intro briefing`,
      `Condition_Intro_Type=Time`,
      `Condition_Intro_Time=${spec.introDelaySeconds}`,
      `ConditionsCompleted=<Intro>`,
      `Action_Taskforce1_Message=IntroMessage`,
      ``,
    ].join("\n"),
    [
      `[Trigger2]`,
      `Name=Primary objective complete`,
      `Condition_PatrolComplete_Type=Time`,
      `Condition_PatrolComplete_Time=${spec.patrolSeconds}`,
      ...(hasEnemies
        ? [
            `Condition_EnemyDestroyed_Type=UnitDestroyed`,
            `Condition_EnemyDestroyed_Units=${enemySections.join(",")}`,
          ]
        : []),
      `ConditionsCompleted=${completionConditions}`,
      `Action_Taskforce1_Message=CompletionMessage`,
      `Action_ObjectivesCompleted=Objective_Primary`,
      `Action_Victory=Taskforce1`,
      `Action_EnableTriggers=Trigger3`,
      `Action_ReactivateTriggers=Trigger3`,
      ``,
    ].join("\n"),
    [
      `[Trigger3]`,
      `Name=Delayed mission exit`,
      `Disabled=True`,
      `Condition_ExitTimer_Type=Time`,
      `Condition_ExitTimer_Time=${spec.exitDelaySeconds}`,
      `ConditionsCompleted=<ExitTimer>`,
      `Action_EndMission=True`,
      ``,
    ].join("\n"),
  ];

  const language = [
    `[Language_en]`,
    `StartIntel=${spec.objectiveText}`,
    `Objective_Primary=${spec.objectiveText}`,
    `IntroMessage=Mission Briefing|${spec.briefing}|Acknowledged`,
    `CompletionMessage=<size=40><color=Lime>MISSION COMPLETE</color></size>|${spec.missionDisplayName}: primary objective achieved. Prepare to return to station.|Continue`,
    ``,
  ].join("\n");

  return [missionLines.join("\n"), ...unitSections, ...triggerSections, language].join("\n");
}

// ---------------------------------------------------------------------------
// Reference-mission merge for unverified [Mission] keys
// ---------------------------------------------------------------------------

/** Keys the generator owns; reference values for these are never copied. */
const OWNED_MISSION_KEY_PATTERNS = [
  /^PlayerTaskforce$/i,
  /^NumberOfTaskforce\d+/i,
  /^NumberOfTriggers$/i,
  /^NumberOfCivilianRoutes$/i,
  /^Taskforce\d+_Formation/i,
];

/**
 * Copy unknown `[Mission]`-section keys (world location, date, environment,
 * etc.) from a read-only base-game reference mission into a generated
 * mission. Only the [Mission] section is merged; no other reference content
 * (units, triggers, language) is copied.
 */
export function mergeReferenceMissionKeys(
  generatedMission: string,
  referenceMissionText: string,
): string {
  // Extract reference [Mission] section key lines.
  const refKeys: string[] = [];
  let inMission = false;
  for (const raw of referenceMissionText.split(/\r?\n/)) {
    const line = raw.replace(/^﻿/, "").trim();
    if (line.startsWith("[")) {
      inMission = /^\[Mission\]/i.test(line);
      continue;
    }
    if (!inMission || line === "" || line.startsWith(";") || line.startsWith("//")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    if (OWNED_MISSION_KEY_PATTERNS.some((p) => p.test(key))) continue;
    refKeys.push(line);
  }
  if (refKeys.length === 0) return generatedMission;

  // Insert after our [Mission] section's own keys (before first blank line
  // following the section header).
  const lines = generatedMission.split("\n");
  const missionIdx = lines.findIndex((l) => l.trim() === "[Mission]");
  if (missionIdx < 0) return generatedMission;
  let insertAt = missionIdx + 1;
  while (insertAt < lines.length && lines[insertAt].trim() !== "" && !lines[insertAt].startsWith("[")) {
    insertAt += 1;
  }
  const annotated = [
    `; --- Keys below copied from read-only reference mission (location/date/environment) ---`,
    ...refKeys,
  ];
  return [...lines.slice(0, insertAt), ...annotated, ...lines.slice(insertAt)].join("\n");
}
